"""Generate examples/notebooks/YDMF-updated.ipynb.

Run this script (from the repo root) to (re)build the updated notebook:

    python examples/notebooks/build_updated_notebook.py

Kept as a script rather than hand-edited JSON so the notebook can be
regenerated cleanly if the ydmf package API changes.
"""

import json
from pathlib import Path

NB_PATH = Path(__file__).parent / "YDMF-updated.ipynb"


def md(*lines):
    return {"cell_type": "markdown", "metadata": {}, "source": [l + "\n" for l in lines[:-1]] + [lines[-1]] if lines else []}


def code(*lines):
    return {
        "cell_type": "code",
        "execution_count": None,
        "metadata": {},
        "outputs": [],
        "source": [l + "\n" for l in lines[:-1]] + ([lines[-1]] if lines else []),
    }


cells = [
    md(
        "# YDMF example: Poisson problem — updated for the `ydmf` package",
        "",
        "This notebook is the **updated** version of `YDMF-original.ipynb`. The",
        "original prototyped a bespoke inline strictyaml schema (`Model` /",
        "`ModelDomain` / `Domain` / `Grid` / `Topology` / `Geometry` / `DataItem`)",
        "directly mirroring XDMF concepts, plus hand-rolled YAML→XDMF XML-writing",
        "code.",
        "",
        "That schema predates (and differs from) the `ydmf` package's actual",
        "`Problem` / `strong_form` / `solution_paths` / `archive` schema — see",
        "`docs/ydmf-schema.md` and `docs/ydmf-schema-v0.2-delta.md`. This notebook",
        "keeps the same worked example (a 3D Poisson problem archived as a",
        "time-collection of tetrahedral meshes in HDF5, per `docs/ydmf-schema.md`",
        "§5 \"XDMF Preservation\") but:",
        "",
        "1. Uses `ydmf.load_ydmf`/`ydmf.validate_ydmf` (real package schema) instead",
        "   of the notebook's private inline `YDMF` strictyaml schema.",
        "2. Uses `ydmf.write_xdmf` (in `src/ydmf/xdmf.py`) instead of the hand-rolled",
        "   `ElementTree` code that used to live directly in the notebook.",
        "3. Demonstrates a full problem-definition YDMF document (physics + weak",
        "   form + discretization) *and* an `Archive.Domain` block for the mesh",
        "   time-series output, since those are two distinct schema sections in",
        "   the current package (the original notebook conflated them into one",
        "   ad hoc structure).",
    ),
    md("## 1. A full YDMF problem document (v0.1-compatible schema)"),
    code(
        "from ydmf import load_ydmf, validate_ydmf, normalize_unknowns",
        "",
        "poisson_problem_yaml = r\"\"\"",
        "Problem:",
        "  name: \"Poisson 3D (unit cube, tetrahedral mesh)\"",
        "  physical_model:",
        "    provenance: llm_derived",
        "    processes: [diffusion]",
        "    assumptions: [steady, constant_properties]",
        "",
        "  strong_form:",
        "    unknowns: [u]",
        "    unknown_provenance: llm_derived",
        "    equation_formulation: \"Poisson\"",
        "    strong_form_expression: |",
        "      Δu = f",
        "    domain: |",
        "      Ω = unit cube [0,1]^3",
        "    boundary_regions:",
        "      - name: \"all_boundaries\"",
        "        geometry: \"∂Ω\"",
        "    coefficients:",
        "      f: \"1.0\"",
        "",
        "  weak_forms:",
        "    - label: \"global\"",
        "      provenance: llm_derived",
        "      derivation: |",
        "        Multiply by test function v ∈ H1_0(Ω), integrate by parts.",
        "      solution_spaces:",
        "        trial: \"H1\"",
        "        test: \"H1_0\"",
        "      bilinear: |",
        "        a(u,v) = ∫Ω ∇u·∇v dx",
        "      linear: |",
        "        l(v) = ∫Ω f·v dx",
        "",
        "solution_paths:",
        "  analytical: []",
        "  discretizations:",
        "    - name: \"P1_tetrahedral\"",
        "      provenance: proteus_derived",
        "      from_weak_form: \"global\"",
        "      finite_element:",
        "        fields: {family: CG, order: 1}",
        "      discretization_details: \"P1 on tetrahedral mesh, 687737 elements\"",
        "      solver:",
        "        type: linear",
        "        linear_solver: petsc",
        "        tolerance: 1e-10",
        "",
        "archive:",
        "  format: xdmf",
        "  time_collection: append",
        "  version: \"ydmf-0.2\"",
        "\"\"\"",
        "",
        "poisson_problem = validate_ydmf(poisson_problem_yaml)",
        "print('Problem name:', poisson_problem['Problem']['name'])",
        "print('Unknowns (normalized):',",
        "      normalize_unknowns(poisson_problem['Problem']['strong_form']['unknowns']))",
    ),
    md(
        "## 2. The mesh archive data (Domain / TimeCollection / Grid)",
        "",
        "This is the part of the original notebook's `poisson_data` YAML that",
        "described the actual mesh time-series (two time steps of a tetrahedral",
        "mesh, backed by HDF5 datasets). In the current schema this corresponds",
        "to `docs/ydmf-schema.md` §5 (\"XDMF Preservation\") — an `Archive.Domain`",
        "block that mirrors XDMF's own `Domain`/`Grid` structure directly, since",
        "*XDMF is a consumer of the archive, not a schema dependency of YDMF*.",
        "",
        "We keep this as a plain Python dict (rather than trying to force it",
        "through the `Problem`-oriented `YDMF_SCHEMA`, which doesn't model mesh",
        "archives — only physics/discretization) and feed it straight to",
        "`ydmf.write_xdmf`.",
    ),
    code(
        "domain = {",
        "    \"TimeCollection\": {",
        "        \"Name\": \"Mesh Spatial_Domain\",",
        "        \"Data\": [",
        "            {",
        "                \"Time\": 0.0,",
        "                \"Topology\": {",
        "                    \"Type\": \"Tetrahedron\",",
        "                    \"NumberOfElements\": 687737,",
        "                    \"DataItem\": {",
        "                        \"Format\": \"HDF\",",
        "                        \"DataType\": \"Int\",",
        "                        \"Dimensions\": [687737, 4],",
        "                        \"Data\": \"poisson_3.h5:/elementsSpatial_Domain0\",",
        "                    },",
        "                },",
        "                \"Geometry\": {",
        "                    \"Type\": \"XYZ\",",
        "                    \"DataItem\": {",
        "                        \"Format\": \"HDF\",",
        "                        \"DataType\": \"Float\",",
        "                        \"Precision\": 8,",
        "                        \"Dimensions\": [118084, 3],",
        "                        \"Data\": \"poisson_3.h5:/nodesSpatial_Domain0\",",
        "                    },",
        "                },",
        "            },",
        "            {",
        "                \"Time\": 1.0,",
        "                \"Topology\": {",
        "                    \"Type\": \"Tetrahedron\",",
        "                    \"NumberOfElements\": 687737,",
        "                    \"DataItem\": {",
        "                        \"Format\": \"HDF\",",
        "                        \"DataType\": \"Int\",",
        "                        \"Dimensions\": [687737, 4],",
        "                        \"Data\": \"poisson_3.h5:/elementsSpatial_Domain1\",",
        "                    },",
        "                },",
        "                \"Geometry\": {",
        "                    \"Type\": \"XYZ\",",
        "                    \"DataItem\": {",
        "                        \"Format\": \"HDF\",",
        "                        \"DataType\": \"Float\",",
        "                        \"Precision\": 8,",
        "                        \"Dimensions\": [118084, 3],",
        "                        \"Data\": \"poisson_3.h5:/nodesSpatial_Domain1\",",
        "                    },",
        "                },",
        "            },",
        "        ],",
        "    }",
        "}",
    ),
    md("## 3. Convert to XDMF using `ydmf.write_xdmf` (package code, not notebook code)"),
    code(
        "from ydmf import write_xdmf",
        "",
        "write_xdmf(domain, \"poisson.xmf\")",
        "",
        "with open(\"poisson.xmf\") as f:",
        "    print(f.read())",
    ),
    md(
        "## 4. What changed vs. the original notebook",
        "",
        "| Original (`YDMF-original.ipynb`) | Updated (this notebook) |",
        "|---|---|",
        "| Inline `Model`/`ModelDomain`/`Domain`/`Grid`/... strictyaml schema defined *in the notebook* | Real `ydmf.YDMF_SCHEMA` from `src/ydmf/schema.py`, versioned and tested |",
        "| One YAML blob conflating physics (`Model.Equation`) and mesh archive (`Domain.TimeCollection`) | Two clear sections: a `Problem`/`solution_paths` document for physics+discretization, and a plain `Archive.Domain` dict for the mesh time-series |",
        "| Hand-rolled `ElementTree` XML-building code, `indentXML()`, pasted inline | `ydmf.write_xdmf()` / `ydmf.build_xdmf_tree()` — tested package functions |",
        "| `dirty_load(..., allow_flow_style=True)` called directly on an ad hoc schema | Same `allow_flow_style=True` need, now handled once inside `ydmf.load_ydmf`/`ydmf.validate_ydmf` so every caller gets it for free |",
        "",
        "The original notebook is preserved unmodified at",
        "`examples/notebooks/YDMF-original.ipynb` for reference.",
    ),
]

notebook = {
    "cells": cells,
    "metadata": {
        "kernelspec": {
            "display_name": "Python 3",
            "language": "python",
            "name": "python3",
        },
        "language_info": {"name": "python", "version": "3.11"},
    },
    "nbformat": 4,
    "nbformat_minor": 5,
}

NB_PATH.write_text(json.dumps(notebook, indent=1, ensure_ascii=False))
print(f"Wrote {NB_PATH}")
